name: Compile Examples

on: [pull_request, push]

jobs:
  compile-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn: [
          "arduino:megaavr:uno2018" #,
          #"arduino:megaavr:nona4809"
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # The source files are in a subfolder of the ArduinoCore-API repository, so it's not possible to clone it directly to the final destination in the core
      - name: Checkout ArduinoCore-API
        uses: actions/checkout@v2
        with:
          repository: arduino/ArduinoCore-API
          path: extras/ArduinoCore-API

      - name: Install ArduinoCore-API
        run: mv "$GITHUB_WORKSPACE/extras/ArduinoCore-API/api" "$GITHUB_WORKSPACE/cores/arduino"

      - name: Checkout Adafruit WiFiNINA
        uses: actions/checkout@v2
        with:
          repository: adafruit/WiFiNINA
          path: libraries/WiFiNINA      

      - name: Compile examples
        uses: arduino/actions/libraries/compile-examples@master
        with:
          fqbn: ${{ matrix.fqbn }}
          libraries: |
            - name: Adafruit IO Arduino
              version: 3.6.0
            - name: Adafruit MQTT Library
              version: 1.0.3
            - name: ArduinoHttpClient
              version: 0.4.0
            # Don't use library manager WiFiNINA
            #  - name: WiFiNINA
            #  version: 1.4.0
            - name: MegunoLink
          platforms: |
            # Use Board Manager to install the latest release of Arduino megaAVR Boards to get the toolchain
            - name: "arduino:megaavr"
            # Overwrite the Board Manager installation with the local platform
            - source-path: "./"
              name: "arduino:megaavr"
          sketch-paths: "extras/AIO_LED_Pot"
          size-report-sketch: 'AIO_LED_Pot'
          enable-size-deltas-report: 'true'
          verbose: 'true'

      - name: Save memory usage change report as artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v1
        with:
          name: 'size-deltas-reports'
          path: 'size-deltas-reports'