name: Compile Examples

on: [pull_request, push]

jobs:
  compile-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn: [
          "arduino:megaavr:uno2018",
          "arduino:megaavr:nona4809"
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # The source files are in a subfolder of the ArduinoCore-API repository, so it's not possible to clone it directly to the final destination in the core
      - name: Checkout ArduinoCore-API
        uses: actions/checkout@v2
        with:
          repository: arduino/ArduinoCore-API
          path: extras/ArduinoCore-API

      - name: Install ArduinoCore-API
        run: mv "$GITHUB_WORKSPACE/extras/ArduinoCore-API/api" "$GITHUB_WORKSPACE/cores/arduino"

      - name: Compile examples
        uses: per1234/actions/libraries/compile-examples@8590db1c2b93c0c51ed131b251d4c86b56c6b1c9
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            # Use Board Manager to install the latest release of Arduino megaAVR Boards to get the toolchain
            - name: "arduino:megaavr"
            # Overwrite the Board Manager installation with the local platform
            - source-path: "./"
              name: "arduino:megaavr"
          sketch-paths: "examples"
          size-report-sketch: 'FONAtest'
          enable-size-deltas-report: 'true'